### ISSUE TITLE
Ledger integration milestone 2

### ISSUE THREAD

**Issue by TobiaszCudnik** [RiseVision/rise-react-wallet#137]
Next milestone for the ledger integration should include:
- [x] merge `LedgerStore` and `LedgerHub`
- [x] remove `LedgerChannel` in favor of `LedgerStore.isOpen`
- [x] `deviceId` should be an observable
- [x] when signing a transaction one have to do it twice
  - first one times out, although the ledger UI guides as expected #224 ([support page](https://support.ledger.com/hc/en-us/articles/360018810413-U2F-timeout-in-Chrome-browser))

**Comment by roosmaa** [comment]
Please can you include motivation behind those items?

Based on that list alone I'm confident this would be going three steps backwards. So here are some comments regarding the items about why they are as they are.

> Store is redundant, hub is enough

The `Store`, `Channel` and `Hub` are there to hide the internals from outside world. No need to give us the chance (in the future) to attempt poking internal things that are not safe to be poked.

> use only one transport and channel

The main reason why the Channel abstraction exists is to make UI layer code a lot simpler to deal with. You create a channel for a component and when that component gets destroyed you simply close that channel, you don't have to worry about the pending async tasks as the LedgerHub takes care of disposing of them cleanly.

> deviceId should be an observable

But it already is: https://github.com/RiseVision/rise-react-wallet/blob/master/src/stores/ledger.ts#L150 (it propagates through via the getters in `Channel` and `Store`).

> replace promises with async

I'm pretty confident you cannot replace promises with async and get codebase that's easier digest than the current one. The executioner needs to be able to trigger the start of a Ledger task and inject the ping task into the queue. Without promises that isn't really possible. Currently async is used where promises aren't absolutely necessary.

**Comment by TobiaszCudnik** [comment]
> Please can you include motivation behind those desired changes?

I will provide detailed info once I assign the ticket and start working on it. Overall the implementation seems too complex, not encapsulated enough and ideally we'd depend on some external module(s).

> The Store, Channel and Hub are there to hide the internals from outside world.

I'm pretty convinced store & hub can be merged for now.

> The main reason why the Channel abstraction exists is to make UI layer code a lot simpler to deal with. 

Could be simplified from the consumer perspective.

> > deviceId should be an observable
> 
> But it already is: https://github.com/RiseVision/rise-react-wallet/blob/master/src/stores/ledger.ts#L150 (it propagates through via the getters in `Channel` and `Store`).

[Not in the store](https://github.com/RiseVision/rise-react-wallet/blob/master/src/stores/ledger.ts#L441), which is the point of @observables.

> this would be going three steps backwards

Theres nothing wrong in going backwards to simplify things, as long as they work equally well.

Also, blocked by #121.

**Comment by roosmaa** [comment]
Ledger things have undergone a refactor, so closing this issue.

**Comment by TobiaszCudnik** [comment]
Ledger's refactoring was related to supporting `ledger-node-hid` module and only partially addressed this ticket. Re opening.

I've updated the todo list in the ticket's description to reflect the current situation.
