### ISSUE TITLE
Validations tracking issue

### ISSUE THREAD

**Issue by TobiaszCudnik** [RiseVision/rise-react-wallet#25]
- [x] register delegate form - username
- [x] register delegate form - balance
- [x] send transaction form - recipient, amount input, balance
- [x] confirm transaction form - mnemonic, 2nd passphrase ([see below](https://github.com/RiseVision/rise-react-wallet/issues/25#issuecomment-416195539)) [#56]
- [x] remove account form
- [x] confirm transaction form - confirm (new) 2nd passphrase  #54
- [x] 2nd passphrase
