### ISSUE TITLE
Ledger support tracking issue

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-react-wallet#55]
We need to implement Ledger hardware wallet support. This is a tracking issue for all the sub-tasks required.

- [ ] confirm account address on Ledger (via account settings) [#115]
- [x] hw-wallet specific transaction confirmation/signing flow UI
- [x] new onboarding page
- [x] communicate using dpos-ledger-api
- [x] test with a real device
- [x] error messages and proper timeouts
