### ISSUE TITLE
Address book tracking issue

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-react-wallet#87]
We need to implement an address book support. This is a tracking issue for all the sub-tasks required.

- [x] Mobx store
- [x] Address book main UI
- [x] Add/modify dialogs
- [x] Hookup transaction details to address book functionality
- [x] Hookup send dialog autocomplete to address book store
- [x] Tests
